# Generated by Django 6.0.5 on 2026-07-07 16:14

import django.core.validators
import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=main.models.brand_image_upload_to, verbose_name='Image')),
                ('show_in_carousel', models.BooleanField(default=False, verbose_name='Show in carousel')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Session key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=main.models.product_main_image_upload_to, verbose_name='Image')),
                ('promo_video', models.FileField(blank=True, null=True, upload_to=main.models.product_video_upload_to, verbose_name='Promo video')),
                ('promo_video_poster', models.ImageField(blank=True, null=True, upload_to=main.models.product_video_poster_upload_to, verbose_name='Promo video poster')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final price')),
                ('sku_root_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SKU root final price')),
                ('sku_root_old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SKU root base price')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%'), (65, '65%'), (70, '70%'), (75, '75%'), (80, '80%'), (85, '85%'), (90, '90%'), (95, '95%'), (100, '100%')], null=True, verbose_name='Discount percent')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('likes_adjustment', models.IntegerField(default=0, verbose_name='Admin likes adjustment')),
                ('badge_type', models.CharField(blank=True, choices=[('', 'No badge'), ('new', 'New'), ('hit', 'Hit'), ('top', 'Top')], default='', max_length=10, verbose_name='Badge')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductAlsoChosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='also_chosen_relations', to='main.product', verbose_name='Product')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='also_chosen_for', to='main.product', verbose_name='Recommended product')),
            ],
            options={
                'verbose_name': 'Also chosen product',
                'verbose_name_plural': 'Also chosen products',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='also_chosen_products',
            field=models.ManyToManyField(blank=True, related_name='chosen_with_products', through='main.ProductAlsoChosen', to='main.product', verbose_name='Также выбирают'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.product_gallery_image_upload_to, verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product like',
                'verbose_name_plural': 'Product likes',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80, verbose_name='Author name')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('text', models.TextField(verbose_name='Review text')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful')),
                ('helpful_adjustment', models.IntegerField(default=0, verbose_name='Admin helpful adjustment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product review',
                'verbose_name_plural': 'Product reviews',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Session key')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='main.productreview', verbose_name='Review')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review helpful vote',
                'verbose_name_plural': 'Review helpful votes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='SKU code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(blank=True, upload_to=main.models.product_variant_image_upload_to, verbose_name='SKU image')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
                'ordering': ('product', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_key', models.BooleanField(default=False, verbose_name='Key characteristic')),
                ('icon', models.CharField(choices=[('sliders', 'Параметры'), ('bloom', 'Растение'), ('sprout', 'Листья'), ('info', 'Общее'), ('spark', 'Особенность'), ('bolt', 'Мощность'), ('drop', 'Жидкость'), ('leaf', 'Состав'), ('flask', 'Формула'), ('battery', 'Аккумулятор'), ('ruler', 'Размер'), ('shield', 'Защита')], default='info', max_length=20, verbose_name='Icon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product specification',
                'verbose_name_plural': 'Product specifications',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.product_variant_image_upload_to, verbose_name='Variant image')),
                ('image_order', models.PositiveIntegerField(default=0, verbose_name='Image order')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product variant',
                'verbose_name_plural': 'Product variants',
                'ordering': ('variant__group__order', 'variant__group__name', 'image_order', 'variant__order', 'variant__name'),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_variant_ids', models.JSONField(blank=True, default=list, verbose_name='Selected variant ids')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='main.product', verbose_name='Product')),
                ('product_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='main.productsku', verbose_name='Product SKU')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='main.productvariant', verbose_name='Product variant')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_on', models.DateField(db_index=True)),
                ('visitor_key', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site visit',
                'verbose_name_plural': 'Site visits',
                'ordering': ('-visited_on', '-created'),
                'constraints': [models.UniqueConstraint(fields=('visited_on', 'visitor_key'), name='main_sitevisit_unique_visitor_per_day')],
            },
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Group name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('kind', models.CharField(blank=True, choices=[('', 'Обычная'), ('color', 'Цвет'), ('flavor', 'Вкус')], default='', editable=False, max_length=16, verbose_name='System group type')),
            ],
            options={
                'verbose_name': 'Variant group',
                'verbose_name_plural': 'Variant groups',
                'ordering': ('order', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'color')), fields=('kind',), name='main_variantgroup_single_color_kind'), models.UniqueConstraint(condition=models.Q(('kind', 'flavor')), fields=('kind',), name='main_variantgroup_single_flavor_kind')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='variant_image_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_products', to='main.variantgroup', verbose_name='Variant image group'),
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('filter_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Filter name')),
                ('color_hex', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must use the #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Physical color')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.variantgroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Variant option',
                'verbose_name_plural': 'Variant options',
                'ordering': ('group__order', 'group__name', 'order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='main.variantoption', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='options',
            field=models.ManyToManyField(related_name='product_skus', to='main.variantoption', verbose_name='Options'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('user',), name='main_cart_unique_active_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', True)), fields=('session_key',), name='main_cart_unique_active_session'),
        ),
        migrations.AddConstraint(
            model_name='productalsochosen',
            constraint=models.UniqueConstraint(fields=('product', 'recommended_product'), name='unique_product_also_chosen_product'),
        ),
        migrations.AddConstraint(
            model_name='productalsochosen',
            constraint=models.CheckConstraint(condition=models.Q(('product', models.F('recommended_product')), _negated=True), name='product_also_chosen_not_self'),
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('user', 'product')},
        ),
        migrations.AddConstraint(
            model_name='productreviewhelpful',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('review', 'user'), name='main_review_helpful_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='productreviewhelpful',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('review', 'session_key'), name='main_review_helpful_unique_session'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'product_variant'), name='main_cartitem_unique_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'product_sku'), name='main_cartitem_unique_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='variantoption',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='main_variantoption_unique_group_name'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant')},
        ),
    ]
