# Generated by Django 6.0.5 on 2026-07-13 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_warehouseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120, verbose_name='Batch title')),
                ('arrived_at', models.DateField(db_index=True, verbose_name='Arrival date')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Batch note')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse batch',
                'verbose_name_plural': 'Warehouse batches',
                'ordering': ('-arrived_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'ordering': ('-received_at', 'name', 'id'), 'verbose_name': 'Warehouse item', 'verbose_name_plural': 'Warehouse items'},
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='received_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Arrival date'),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.warehousebatch', verbose_name='Warehouse batch'),
        ),
    ]
