# Generated by Django 6.0.5 on 2026-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_available_sizes_product_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.JSONField(blank=True, default=dict, verbose_name='Бейдж (новинка, скидка и т.д.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.BooleanField(default=False, verbose_name='Понравился текущему пользователю'),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
