# Generated by Django 6.0.5 on 2026-06-09 16:55

from django.db import migrations, models


def copy_variants_to_available(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.available_variants = product.variants or []
        product.save(update_fields=('available_variants',))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_variants',
            field=models.JSONField(blank=True, default=list, verbose_name='Available variants'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list, verbose_name='All variants'),
        ),
        migrations.RunPython(copy_variants_to_available, migrations.RunPython.noop),
    ]
