# Generated by Django 6.0.5 on 2026-06-09 18:18

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def unique_slug(model, base_value):
    base_slug = slugify(base_value) or "variant"
    slug = base_slug
    index = 2
    while model.objects.filter(slug=slug).exists():
        slug = f"{base_slug}-{index}"
        index += 1
    return slug


def migrate_json_variants(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    VariantOption = apps.get_model("main", "VariantOption")
    ProductVariant = apps.get_model("main", "ProductVariant")

    for product in Product.objects.select_related("category").all():
        raw_variants = list(product.variants or [])
        raw_available = list(product.available_variants or [])
        labels = []
        for value in raw_variants + raw_available:
            label = str(value).strip()
            if label and label not in labels:
                labels.append(label)

        available_labels = {str(value).strip() for value in raw_available if str(value).strip()}

        for order, label in enumerate(labels):
            variant, _ = VariantOption.objects.get_or_create(
                category=product.category,
                name=label,
                defaults={
                    "slug": unique_slug(VariantOption, f"{product.category.slug}-{label}"),
                    "order": order,
                },
            )
            is_available = label in available_labels
            ProductVariant.objects.get_or_create(
                product=product,
                variant=variant,
                defaults={
                    "stock": 1 if is_available else 0,
                    "available": is_available,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_product_available_variants_alter_product_variants"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group", models.CharField(blank=True, max_length=80, verbose_name="Group")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=120, verbose_name="Slug")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="variant_options", to="main.category", verbose_name="Category")),
            ],
            options={
                "verbose_name": "Variant option",
                "verbose_name_plural": "Variant options",
                "ordering": ("category__name", "group", "order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                ("available", models.BooleanField(default=False, verbose_name="Available")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_variants", to="main.product", verbose_name="Product")),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_variants", to="main.variantoption", verbose_name="Variant")),
            ],
            options={
                "verbose_name": "Product variant",
                "verbose_name_plural": "Product variants",
                "ordering": ("variant__group", "variant__order", "variant__name"),
            },
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(fields=("category", "name"), name="main_variantoption_unique_category_name"),
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(condition=models.Q(("category__isnull", True)), fields=("name",), name="main_variantoption_unique_global_name"),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "variant")},
        ),
        migrations.RunPython(migrate_json_variants, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="available_variants",
        ),
        migrations.RemoveField(
            model_name="product",
            name="variants",
        ),
    ]
