# Generated by Django 6.0.5 on 2026-07-15 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_warehouse_shipment_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_off_at', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Write-off date')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Write-off note')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse write-off',
                'verbose_name_plural': 'Warehouse write-offs',
                'ordering': ('-written_off_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WarehouseWriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=140, verbose_name='Item name')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_entries', to='main.warehouseitem', verbose_name='Warehouse item')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.warehousewriteoff', verbose_name='Warehouse write-off')),
            ],
            options={
                'verbose_name': 'Warehouse write-off item',
                'verbose_name_plural': 'Warehouse write-off items',
                'ordering': ('id',),
            },
        ),
    ]
