# Generated by Django 6.0.5 on 2026-07-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_warehousewriteoff_warehousewriteoffitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warehouseshipmentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('ttn', ''), _negated=True), fields=('ttn',), name='unique_non_empty_warehouse_shipment_ttn'),
        ),
    ]
