# Generated by Django 6.0.5 on 2026-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_warehouseshipmentorder_unique_non_empty_warehouse_shipment_ttn'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePointsWeekClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(db_index=True, max_length=7, verbose_name='Points month')),
                ('period_start', models.DateTimeField(verbose_name='Period start')),
                ('period_end', models.DateTimeField(verbose_name='Period end')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Warehouse points week close',
                'verbose_name_plural': 'Warehouse points week closes',
                'ordering': ('-period_end', '-id'),
            },
        ),
    ]
