# Generated by Django 6.0.5 on 2026-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_warehousepointsweekclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseshipmentorder',
            name='points_closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Points closed at'),
        ),
    ]
