# Generated by Django 6.0.5 on 2026-06-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_specifications_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/%Y/%m/%d/', verbose_name='Promo video'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='products/videos/posters/%Y/%m/%d/', verbose_name='Promo video poster'),
        ),
    ]
