# Generated by Django 6.0.5 on 2026-06-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_promo_video_product_promo_video_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlsoChosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='also_chosen_relations', to='main.product', verbose_name='Product')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='also_chosen_for', to='main.product', verbose_name='Recommended product')),
            ],
            options={
                'verbose_name': 'Also chosen product',
                'verbose_name_plural': 'Also chosen products',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='also_chosen_products',
            field=models.ManyToManyField(blank=True, related_name='chosen_with_products', through='main.ProductAlsoChosen', to='main.product', verbose_name='Также выбирают'),
        ),
        migrations.AddConstraint(
            model_name='productalsochosen',
            constraint=models.UniqueConstraint(fields=('product', 'recommended_product'), name='unique_product_also_chosen_product'),
        ),
        migrations.AddConstraint(
            model_name='productalsochosen',
            constraint=models.CheckConstraint(condition=models.Q(('product', models.F('recommended_product')), _negated=True), name='product_also_chosen_not_self'),
        ),
    ]
