# Generated by Django 6.0.5 on 2026-06-15 21:28

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_productalsochosen_product_also_chosen_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.product_main_image_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to=main.models.product_video_upload_to, verbose_name='Promo video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_video_poster',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.product_video_poster_upload_to, verbose_name='Promo video poster'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=main.models.product_gallery_image_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.product_variant_image_upload_to, verbose_name='Variant image'),
        ),
    ]
