# Generated by Django 6.0.5 on 2026-06-17 21:31

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_image_alter_product_promo_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='SKU code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(blank=True, upload_to=main.models.product_variant_image_upload_to, verbose_name='SKU image')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('options', models.ManyToManyField(related_name='product_skus', to='main.variantoption', verbose_name='Options')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
                'ordering': ('product', 'sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='main.productsku', verbose_name='Product SKU'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'product_sku'), name='main_cartitem_unique_product_sku'),
        ),
    ]
