# Generated by Django 6.0.5 on 2026-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_productsku_cartitem_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantoption',
            options={'ordering': ('group', 'order', 'name'), 'verbose_name': 'Variant option', 'verbose_name_plural': 'Variant options'},
        ),
        migrations.RemoveConstraint(
            model_name='variantoption',
            name='main_variantoption_unique_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='variantoption',
            name='main_variantoption_unique_global_name',
        ),
        migrations.AddConstraint(
            model_name='variantoption',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='main_variantoption_unique_group_name'),
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='category',
        ),
    ]
