# Generated by Django 6.0.5 on 2026-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_variantgroup_variantoption_group_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('', 'No badge'), ('new', 'New'), ('hit', 'Hit'), ('top', 'Top')], default='', max_length=10, verbose_name='Badge'),
        ),
    ]
