# Generated by Django 6.0.5 on 2026-06-22 17:41

from django.db import migrations
from django.utils.html import strip_tags


def migrate_legacy_specifications(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    ProductSpecification = apps.get_model("main", "ProductSpecification")
    new_specifications = []

    products = Product.objects.exclude(specifications_text="").exclude(specifications_text__isnull=True)
    for product in products.iterator():
        existing = set(
            ProductSpecification.objects.filter(product_id=product.pk).values_list("name", "value")
        )
        next_order = (
            ProductSpecification.objects.filter(product_id=product.pk)
            .order_by("-order")
            .values_list("order", flat=True)
            .first()
            or 0
        )
        if existing:
            next_order += 1

        for line in str(product.specifications_text or "").splitlines():
            cleaned_line = strip_tags(line).strip()
            if not cleaned_line or ":" not in cleaned_line:
                continue
            name, value = (part.strip() for part in cleaned_line.split(":", 1))
            if not name or not value or len(name) > 120 or len(value) > 255:
                continue
            if (name, value) in existing:
                continue
            new_specifications.append(
                ProductSpecification(
                    product_id=product.pk,
                    name=name,
                    value=value,
                    order=next_order,
                )
            )
            existing.add((name, value))
            next_order += 1

    ProductSpecification.objects.bulk_create(new_specifications)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_product_badge_type'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_specifications, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='specifications_text',
        ),
    ]
