# Generated by Django 6.0.5 on 2026-06-26 18:27

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_product_sku_root_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.brand_image_upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='show_in_carousel',
            field=models.BooleanField(default=False, verbose_name='Show in carousel'),
        ),
    ]
