# Generated by Django 6.0.5 on 2026-06-27 11:44

from django.db import migrations, models


def populate_variant_filter_names(apps, schema_editor):
    VariantOption = apps.get_model('main', 'VariantOption')
    for option in VariantOption.objects.filter(filter_name='').only('id', 'name'):
        option.filter_name = option.name
        option.save(update_fields=('filter_name',))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_brand_image_brand_show_in_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantoption',
            name='filter_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Filter name'),
        ),
        migrations.RunPython(populate_variant_filter_names, migrations.RunPython.noop),
    ]
