# Generated by Django 6.0.5 on 2026-06-28 10:42

import django.db.models.deletion
from django.db import migrations, models


def populate_product_variant_image_groups(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    ProductVariant = apps.get_model('main', 'ProductVariant')

    for product in Product.objects.filter(product_variants__isnull=False).distinct().only('id'):
        variants = ProductVariant.objects.filter(product_id=product.pk)
        image_group_id = (
            variants.exclude(image='')
            .values_list('variant__group_id', flat=True)
            .first()
        )
        if not image_group_id:
            group_ids = list(
                variants.order_by().values_list('variant__group_id', flat=True).distinct()[:2]
            )
            image_group_id = group_ids[0] if len(group_ids) == 1 else None
        if image_group_id:
            Product.objects.filter(pk=product.pk).update(variant_image_group_id=image_group_id)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_variantoption_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_image_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_products', to='main.variantgroup', verbose_name='Variant image group'),
        ),
        migrations.RunPython(populate_product_variant_image_groups, migrations.RunPython.noop),
    ]
