# Generated by Django 6.0.5 on 2026-06-28 10:52

from django.db import migrations, models


def populate_variant_image_order(apps, schema_editor):
    ProductVariant = apps.get_model('main', 'ProductVariant')
    current_key = None
    position = 0
    variants = ProductVariant.objects.select_related('variant').order_by(
        'product_id',
        'variant__group_id',
        'variant__order',
        'variant__name',
        'id',
    )
    for product_variant in variants:
        key = (product_variant.product_id, product_variant.variant.group_id)
        if key != current_key:
            current_key = key
            position = 0
        ProductVariant.objects.filter(pk=product_variant.pk).update(image_order=position)
        position += 1


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_product_variant_image_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('variant__group__order', 'variant__group__name', 'image_order', 'variant__order', 'variant__name'), 'verbose_name': 'Product variant', 'verbose_name_plural': 'Product variants'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Image order'),
        ),
        migrations.RunPython(populate_variant_image_order, migrations.RunPython.noop),
    ]
