# Generated by Django 6.0.5 on 2026-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes_adjustment',
            field=models.IntegerField(default=0, verbose_name='Admin likes adjustment'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='helpful_adjustment',
            field=models.IntegerField(default=0, verbose_name='Admin helpful adjustment'),
        ),
    ]
