# Generated by Django 6.0.5 on 2026-07-01 15:35

import django.core.validators
from django.db import migrations, models


COLOR_MAP = {
    'белый': '#F4F4F4',
    'бежевый': '#D6C4A8',
    'голубой': '#38BDF8',
    'желтый': '#FACC15',
    'жёлтый': '#FACC15',
    'зеленый': '#22C55E',
    'зелёный': '#22C55E',
    'золотой': '#D4A017',
    'коричневый': '#8B5E3C',
    'красный': '#DC3545',
    'оранжевый': '#F97316',
    'розовый': '#EC4899',
    'серебристый': '#B8BDC7',
    'серый': '#808080',
    'синий': '#2563EB',
    'фиолетовый': '#7C3AED',
    'черный': '#111111',
    'чёрный': '#111111',
    'white': '#F4F4F4',
    'black': '#111111',
    'red': '#DC3545',
    'blue': '#2563EB',
    'green': '#22C55E',
    'grey': '#808080',
    'gray': '#808080',
    'purple': '#7C3AED',
}


def create_system_color_group(apps, schema_editor):
    VariantGroup = apps.get_model('main', 'VariantGroup')
    VariantOption = apps.get_model('main', 'VariantOption')

    color_group = VariantGroup.objects.filter(name__iexact='Цвет').first()
    if color_group is None:
        color_group = VariantGroup.objects.create(
            name='Цвет',
            slug='color',
            order=0,
            kind='color',
        )
    else:
        VariantGroup.objects.filter(pk=color_group.pk).update(name='Цвет', kind='color')

    for option in VariantOption.objects.filter(group_id=color_group.pk):
        lookup_name = (option.filter_name or option.name or '').strip().casefold()
        color_hex = COLOR_MAP.get(lookup_name, '')
        if color_hex:
            VariantOption.objects.filter(pk=option.pk).update(color_hex=color_hex)


def reset_system_color_group(apps, schema_editor):
    VariantGroup = apps.get_model('main', 'VariantGroup')
    VariantOption = apps.get_model('main', 'VariantOption')
    color_group_ids = list(
        VariantGroup.objects.filter(kind='color').values_list('pk', flat=True)
    )
    VariantOption.objects.filter(group_id__in=color_group_ids).update(color_hex='')
    VariantGroup.objects.filter(pk__in=color_group_ids).update(kind='')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_product_likes_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Обычная'), ('color', 'Цвет')], default='', editable=False, max_length=16, verbose_name='System group type'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must use the #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Physical color'),
        ),
        migrations.RunPython(create_system_color_group, reset_system_color_group),
        migrations.AddConstraint(
            model_name='variantgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'color')), fields=('kind',), name='main_variantgroup_single_color_kind'),
        ),
    ]
