# Generated by Django 6.0.5 on 2026-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_variantgroup_kind_variantoption_color_hex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_on', models.DateField(db_index=True)),
                ('visitor_key', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site visit',
                'verbose_name_plural': 'Site visits',
                'ordering': ('-visited_on', '-created'),
                'constraints': [models.UniqueConstraint(fields=('visited_on', 'visitor_key'), name='main_sitevisit_unique_visitor_per_day')],
            },
        ),
    ]
